export const movieData = [
  {
    title: "The Lost Girl",
    img: "https://streamo.vuejstemplate.com/images/product/movie-07.jpg",
    date: "2022-03-28",
    category: "latest",
  },
  {
    title: "The Walk",
    img: "https://streamo.vuejstemplate.com/images/product/movie-06.jpg",
    date: "2022-02-02",
    category: "latest",
  },
  {
    title: "Never Stop Looking",
    img: "https://streamo.vuejstemplate.com/images/product/comedy-series-1.png",
    date: "2022-02-01",
    category: "latest",
  },
  {
    title: "Silkovettes In The Attic",
    img: "https://streamo.vuejstemplate.com/images/product/movie-05.jpg",
    date: "2021-12-24",
    category: "latest",
  },
  {
    title: "Two Paglo",
    img: "https://streamo.vuejstemplate.com/images/product/movie-04.jpg",
    date: "2021-12-24",
    category: "latest",
  },
  {
    title: "Love Africa",
    img: "https://streamo.vuejstemplate.com/images/product/movie-03.jpg",
    date: "2021-10-12",
    category: "latest",
  },
  {
    title: "Charging To Victory",
    img: "https://streamo.vuejstemplate.com/images/product/movie-01.jpg",
    date: "2021-08-22",
    category: "latest",
  },
  {
    title: "The Haunting of Hill House",
    img: "https://streamo.vuejstemplate.com/images/product/movie-08.jpg",
    date: "2018-10-12",
    category: "horror",
  },
  {
    title: "Get Out",
    img: "https://streamo.vuejstemplate.com/images/product/movie-09.jpg",
    date: "2017-02-24",
    category: "horror",
  },
  {
    title: "A Quiet Place",
    img: "https://streamo.vuejstemplate.com/images/product/movie-10.jpg",
    date: "2018-04-06",
    category: "horror",
  },
  {
    title: "Hereditary",
    img: "https://streamo.vuejstemplate.com/images/product/movie-11.jpg",
    date: "2018-06-08",
    category: "horror",
  },
  {
    title: "It",
    img: "https://streamo.vuejstemplate.com/images/product/movie-12.jpg",
    date: "2017-09-08",
    category: "horror",
  },
  {
    title: "The Conjuring",
    img: "https://streamo.vuejstemplate.com/images/product/movie-13.jpg",
    date: "2013-07-19",
    category: "horror",
  },
  {
    title: "Annabelle",
    img: "https://streamo.vuejstemplate.com/images/product/movie-14.jpg",
    date: "2014-10-03",
    category: "horror",
  },
  {
    title: "Midsommar",
    img: "https://streamo.vuejstemplate.com/images/product/movie-15.jpg",
    date: "2019-07-03",
    category: "horror",
  },
  {
    title: "The Lost Girl",
    img: "https://streamo.vuejstemplate.com/images/product/horror-12.jpg",
    price: "300Tk",
    originalPrice: "350Tk",
    category: "WatchWithFamily",
  },
  {
    title: "Silkovettes In The Attic",
    img: "https://streamo.vuejstemplate.com/images/product/horror-11.jpg",
    price: "500Tk",
    originalPrice: "550Tk",
    category: "WatchWithFamily",
  },
  {
    title: "Two Paglo",
    img: "https://streamo.vuejstemplate.com/images/product/movie-12.jpg",
    price: "200Tk",
    originalPrice: "250Tk",
    category: "WatchWithFamily",
  },
  {
    title: "Family Adventures",
    img: "https://streamo.vuejstemplate.com/images/product/movie-11.jpg",
    price: "350Tk",
    originalPrice: "400Tk",
    category: "WatchWithFamily",
  },
  {
    title: "The Journey",
    img: "https://streamo.vuejstemplate.com/images/product/horror-6.jpg",
    price: "400Tk",
    originalPrice: "450Tk",
    category: "WatchWithFamily",
  },
  {
    title: "Magical Forest",
    img: "https://streamo.vuejstemplate.com/images/product/movie-10.jpg",
    price: "250Tk",
    originalPrice: "300Tk",
    category: "WatchWithFamily",
  },
];
